export const Tags = [
  'computer science',
  'data science',
  'ecommerce',
  'medicine',
  'biology',
  'chemistry',
  'physics',
  'mathematics',
  'statistics',
  'economics',
  'finance',
  'accounting',
  'business',
  'marketing',
  'law',
  'politics',
  'history',
  'philosophy',
  'psychology',
  'sociology',
  'anthropology',
  'geography',
  'geology',
  'astronomy',
  'engineering',
  'architecture',
  'art',
  'music',
  'film',
  'theater',
  'literature',
  'language',
  'religion',
  'fashion',
  'food',
  'travel',
  'sports',
  'gaming',
  'programming',
  'web development',
  'mobile development',
  'game development',
  'machine learning',
  'artificial intelligence',
  'blockchain',
  'cryptocurrency',
  'cybersecurity',
  'data analytics',
  'data visualization',
  'digital marketing',
  'digital transformation',
  'entrepreneurship',
  'leadership',
  'management',
  'project management',
  'social media',
  'software engineering',
  'ux design',
  'ui design',
  'web design',
  'web hosting',
  'web security',
  'web services',
  'web technologies',
  'web tools',
  'web trends',
]
